github_api_token: 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

plot_color: red

plot_title: 'job plot'

plot_x_axis_title: 'job x-axis'

plot_y_axis_title: 'job y-axis'

figure_size: 100

default_save_path:
