github_api_token: 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

plot_color: red

plot_title: 'job plot'

plot_x_axis_title: 'job x-axis'

plot_y_axis_title: 'job y-axis'

figure_size: 100

default_save_path:
