github_api_token: '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'

plot_color: 'blue'

plot_title: 

plot_x_axis_title:

plot_y_axis_title:

figure_size:

default_save_path: 
