github_api_token: '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'

plot_color: 

plot_title: 

plot_x_axis_title:

plot_y_axis_title:

figure_size:

default_save_path: 
